import {Bug} from '../models/bug';

export const demoData: Bug[] = [
    {
        id: 404195,
        key: 'DATALM-91934',
        link: 'https://jira.mohaymen.ir/browse/DATALM-91934',
        assignee: 'بیژن عیسی‌پور',
        component: 'IST TDW',
        creationDate: '2022-09-28, 09:36:13',
        labels: 'Annoying | Sorting | TAX-DAS',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'باگ عدم اعمال تنظیمات رده بندی',
        version: 21,
        sla: -6836491,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 408920,
        key: 'DATALM-92183',
        link: 'https://jira.mohaymen.ir/browse/DATALM-92183',
        assignee: 'بیژن عیسی‌پور',
        component: 'BMK FMS',
        creationDate: '2022-10-11, 14:37:36',
        labels: 'PADW',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'اشکال در بروزرسانی پایگاه داده padw',
        version: 21,
        sla: -5972492,
        slaColor: 'قرمز',
        starCis: 'PADW',
    },
    {
        id: 412018,
        key: 'DATALM-93118',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93118',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2022-10-18, 07:27:00',
        labels: 'DisplayConfigs',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'کار نکردن رگرسیون',
        version: 24,
        sla: -5454092,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 412174,
        key: 'DATALM-93141',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93141',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2022-10-18, 12:04:45',
        labels: 'Oracle | PADW',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'ارائه خطا با انتخاب منبع داده‌ی اتصالی از PADW',
        version: 24,
        sla: -5454092,
        slaColor: 'قرمز',
        starCis: 'PADW',
    },
    {
        id: 412021,
        key: 'DATALM-93120',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93120',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-10-18, 07:48:48',
        labels: 'DisplayConfigs',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'فریز شدن صفحه در حالت خاص تنظیم آستانه محور عمودی',
        version: 24,
        sla: -5454092,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 412254,
        key: 'DATALM-93147',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93147',
        assignee: 'پارسا اروانه',
        component: 'IST TDW',
        creationDate: '2022-10-18, 14:42:12',
        labels: 'FrontendPerformance',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'طراحی - داشبورد - مصرف بالای CPU در سمت کلاینت',
        version: 21,
        sla: -5454092,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 414523,
        key: 'DATALM-93320',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93320',
        assignee: 'پارسا اروانه',
        component: 'BMK FMS',
        creationDate: '2022-10-26, 14:57:58',
        labels: 'Navigation',
        priority: 2,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'مشکل باگ در بخش تعامل pa (استفاده از متغیر تاریخ)',
        version: 21,
        sla: -5342613,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 415102,
        key: 'DATALM-93381',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93381',
        assignee: 'بیژن عیسی‌پور',
        component: 'IST TDW',
        creationDate: '2022-10-29, 12:54:55',
        labels: 'HelpNeeded',
        priority: 2,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'باگ تغییر گزارشات سرویس داده ای',
        version: 21,
        sla: -5177193,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 412352,
        key: 'DATALM-93164',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93164',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-10-18, 18:39:14',
        labels: 'Other',
        priority: 5,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خطا در هنگام استفاده از شکست و نمایش سایر باهمدیگر',
        version: 24,
        sla: -4935692,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 416375,
        key: 'DATALM-93475',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93475',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2022-11-01, 09:37:31',
        labels: '24 | PADW',
        priority: 3,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'عدم ارائه خطا در مرحله ایجاد منبع داده در صورت وجود رکورد یکسان در ستون بُعد',
        version: 24,
        sla: -4676493,
        slaColor: 'قرمز',
        starCis: 'PADW',
    },
    {
        id: 414928,
        key: 'DATALM-93350',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93350',
        assignee: 'بیژن عیسی‌پور',
        component: 'RMT ITS',
        creationDate: '2022-10-29, 10:43:40',
        labels: 'Oracle | PADW',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خطای محدودیت تعداد پارامتر ارسالی در لیست',
        version: 21,
        sla: -4676493,
        slaColor: 'قرمز',
        starCis: 'PADW',
    },
    {
        id: 415456,
        key: 'DATALM-93392',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93392',
        assignee: 'پارسا اروانه',
        component: 'RMT ITS',
        creationDate: '2022-10-30, 10:14:01',
        labels: 'UI',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'عدم ثابت ماندن تصویر گزارش',
        version: 21,
        sla: -4590093,
        slaColor: 'قرمز',
        starCis: 'PADW',
    },
    {
        id: 417619,
        key: 'DATALM-93567',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93567',
        assignee: 'پارسا اروانه',
        component: 'IST TDW',
        creationDate: '2022-11-05, 16:25:23',
        labels: 'UI',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'تغییر کشیدگی گزارشات درون داشبورد در حالت مشاهده و ویرایش',
        version: 21,
        sla: -4158093,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 418300,
        key: 'DATALM-93614',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93614',
        assignee: 'بیژن عیسی‌پور',
        component: 'IST TDW',
        creationDate: '2022-11-07, 12:32:17',
        labels: 'Other | معماری',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'مشکل ایجاد ستون سایر هنگامی که نیاز نیست در گزارش ستونی',
        version: 21,
        sla: -3985293,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 418948,
        key: 'DATALM-93655',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93655',
        assignee: 'پارسا اروانه',
        component: 'RMT ITS',
        creationDate: '2022-11-08, 16:31:53',
        labels: 'Drilldown',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'غیرفعال بودن دکمه بازگشت در گزارش دولایه',
        version: 21,
        sla: -3898893,
        slaColor: 'قرمز',
        starCis: 'PADW',
    },
    {
        id: 419326,
        key: 'DATALM-93679',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93679',
        assignee: 'بیژن عیسی‌پور',
        component: 'RMT ITS',
        creationDate: '2022-11-09, 15:24:22',
        labels: 'Drilldown',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'عدم اعمال فیلترهای داشبورد در گزارش نقشه ایران حالت لایه ای',
        version: 21,
        sla: -3812493,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 421491,
        key: 'DATALM-93838',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93838',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2022-11-16, 12:47:17',
        labels: 'Connection',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'عدم کارکرد مکانیزم انتخاب آخرین اتصال تغییر داده شده',
        version: 24,
        sla: -3294093,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 424964,
        key: 'DATALM-93993',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93993',
        assignee: 'بیژن عیسی‌پور',
        component: 'MOH BAS',
        creationDate: '2022-11-27, 13:16:37',
        labels: 'SpecialCondition',
        priority: 2,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خطا در مشاهده داده نمودار',
        version: 21,
        sla: -3015888,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 418746,
        key: 'DATALM-93642',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93642',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-11-08, 11:26:15',
        labels: '24 | UI',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'نمایش فاصله در باکس تاریخ زمان',
        version: 24,
        sla: -2952461,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 425036,
        key: 'DATALM-93996',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93996',
        assignee: 'بیژن عیسی‌پور',
        component: 'MOH BAS',
        creationDate: '2022-11-27, 15:23:48',
        labels: 'SpecialCondition',
        priority: 2,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خطا در لود نمودارمحدوده ای',
        version: 21,
        sla: -3008256,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 425087,
        key: 'DATALM-93998',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93998',
        assignee: 'بیژن عیسی‌پور',
        component: 'IST TDW',
        creationDate: '2022-11-27, 17:01:22',
        labels: 'Sorting',
        priority: 2,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'مشکل در مرتب سازی در نمودار گرید',
        version: 21,
        sla: -3002402,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 429261,
        key: 'DATALM-94255',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94255',
        assignee: 'پارسا اروانه',
        component: 'RMT ITS',
        creationDate: '2022-12-11, 08:10:41',
        labels: 'MohaymenGrid',
        priority: 2,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'باگ عدم نمایش تعداد کل رکوردا و صفحه بندی جدول',
        version: 21,
        sla: -1997445,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 427684,
        key: 'DATALM-94147',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94147',
        assignee: 'بیژن عیسی‌پور',
        component: 'IST TDW',
        creationDate: '2022-12-05, 17:19:05',
        labels: 'Validation',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'باقی ماندن خطای تعامل، هنگامی که تعامل را حذف میکنیم',
        version: 21,
        sla: -1911694,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 430356,
        key: 'DATALM-94356',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94356',
        assignee: 'بیژن عیسی‌پور',
        component: 'MOH LES',
        creationDate: '2022-12-13, 09:51:09',
        labels: 'Connection | HelpNeeded',
        priority: 2,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خطای Value cannot be null. هنگام لود نمودارها',
        version: 21,
        sla: -1818613,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 430795,
        key: 'DATALM-94397',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94397',
        assignee: 'بیژن عیسی‌پور',
        component: 'IST TDW',
        creationDate: '2022-12-14, 13:15:15',
        labels: 'MigratingFrom21To24',
        priority: 2,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خطای مقدار یکی از شی ها تهی است، PA 24',
        version: 24,
        sla: -1804575,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 430895,
        key: 'DATALM-94558',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94558',
        assignee: 'بیژن عیسی‌پور',
        component: 'IST TDW',
        creationDate: '2022-12-14, 14:52:38',
        labels: 'MigratingFrom21To24',
        priority: 2,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'عدم دریافت مقادیر پیش فرض در PA 24',
        version: 24,
        sla: -1714127,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 430605,
        key: 'DATALM-94376',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94376',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-12-13, 18:50:30',
        labels: 'UI',
        priority: 3,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'اعداد انگلیسی در متون فارسی',
        version: 24,
        sla: -1566094,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 430577,
        key: 'DATALM-94369',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94369',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-12-13, 16:57:49',
        labels: 'ObjectFramework',
        priority: 3,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'کار نکردن tree-select هنگان ذخیره آبجکت',
        version: 24,
        sla: -1566094,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 430789,
        key: 'DATALM-94396',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94396',
        assignee: 'میلاد نفر',
        component: 'IST TDW',
        creationDate: '2022-12-14, 13:03:09',
        labels: 'MigratingFrom21To24',
        priority: 2,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'عدم امکان راست کلیک در گزارش، نسخه pa 24',
        version: 24,
        sla: -1493676,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 432075,
        key: 'DATALM-94773',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94773',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2022-12-18, 15:56:02',
        labels: 'HelpNeeded',
        priority: 3,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خطا هنگام پیش نمایش گزارش معمولی',
        version: 25,
        sla: -1220494,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 428166,
        key: 'DATALM-94168',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94168',
        assignee: 'میلاد نفر',
        component: '',
        creationDate: '2022-12-07, 10:38:53',
        labels: 'ChartDesignPipeline',
        priority: 5,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خطا هنگام تغییر نام ستون تجمیع شده',
        version: 24,
        sla: -1220494,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 421067,
        key: 'DATALM-93826',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93826',
        assignee: 'پارسا اروانه',
        component: 'MOH LES',
        creationDate: '2022-11-15, 11:55:44',
        labels: 'UI',
        priority: 6,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'وجود undefined در پنجره ایجاد اتصال',
        version: 21,
        sla: -1049012,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 421938,
        key: 'DATALM-93863',
        link: 'https://jira.mohaymen.ir/browse/DATALM-93863',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-11-19, 09:32:04',
        labels: 'TimeDrivenCharts',
        priority: 6,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خطا در پیش نمایش الگوی خطی - زمانی',
        version: 24,
        sla: -1047695,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 431293,
        key: 'DATALM-94708',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94708',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2022-12-17, 10:30:24',
        labels: 'DashboardSettings',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'داشبورد - عدم نمایش حاشیه فریم گزارش‌ها',
        version: 25,
        sla: -1047695,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 432333,
        key: 'DATALM-94784',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94784',
        assignee: 'بیژن عیسی‌پور',
        component: 'MOH LES',
        creationDate: '2022-12-19, 12:45:28',
        labels: 'PublicView',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خطای از بین  رفتن شناسه هویتی هنگام باز کردن لینک عمومی داشبورد',
        version: 21,
        sla: -870836,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 430062,
        key: 'DATALM-94329',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94329',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2022-12-12, 12:51:06',
        labels: '',
        priority: 5,
        resolutionDate: null,
        status: 'New',
        summary: 'عدم اعتبارسنجی مناسب ',
        version: 25,
        sla: -800014,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 432960,
        key: 'DATALM-94829',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94829',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-12-20, 19:38:37',
        labels: 'ENGLISH | UI',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'جای اشتباه دکمه تغییر عکس پروفایل',
        version: 24,
        sla: -788495,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 432959,
        key: 'DATALM-94828',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94828',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-12-20, 19:37:39',
        labels: 'ENGLISH | UI',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'پخش اشتباه انیمیشن',
        version: 24,
        sla: -788495,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 433955,
        key: 'DATALM-94905',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94905',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2022-12-24, 18:15:11',
        labels: 'GIS',
        priority: 3,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'بیرون انداختن کاربر در تمپلیت موقعیت مکانی',
        version: 25,
        sla: -788495,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 433953,
        key: 'DATALM-94904',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94904',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2022-12-24, 18:10:31',
        labels: 'GIS',
        priority: 3,
        resolutionDate: null,
        status: 'Confirmed',
        summary: '  خطای بدون دلیل اعتبارسنجی در تمپلیت موقعیت مکانی ',
        version: 25,
        sla: -788495,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 433170,
        key: 'DATALM-94858',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94858',
        assignee: 'بیژن عیسی‌پور',
        component: 'CBI KFS',
        creationDate: '2022-12-21, 13:04:03',
        labels: 'Navigation',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'باگ اضافه کردن تعامل به نمودارهای یک داشبورد',
        version: 21,
        sla: -702095,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 433168,
        key: 'DATALM-94857',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94857',
        assignee: 'بیژن عیسی‌پور',
        component: 'CBI KFS',
        creationDate: '2022-12-21, 13:03:33',
        labels: 'Parameter',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'نمایش ندادن پارامتر داشبورد در حالت مشاهده',
        version: 21,
        sla: -702096,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 433165,
        key: 'DATALM-94856',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94856',
        assignee: 'بیژن عیسی‌پور',
        component: 'CBI KFS',
        creationDate: '2022-12-21, 12:58:10',
        labels: 'Drilldown',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'نداشتن کلید بازگشت به لایه قبل در حالت پنهان تنظیمات داشبورد',
        version: 21,
        sla: -702096,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 435107,
        key: 'DATALM-95018',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95018',
        assignee: '',
        component: '',
        creationDate: '2022-12-28, 19:19:16',
        labels: 'HelpNeeded',
        priority: 1,
        resolutionDate: null,
        status: 'New',
        summary: 'انبارداده تحلیل عملکرد-بروز خطا هنگام را کردن مایگریشن فریمورک روی یک دیتابیس خاص',
        version: 21,
        sla: -912467,
        slaColor: 'قرمز',
        starCis: 'PADW',
    },
    {
        id: 435108,
        key: 'DATALM-95019',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95019',
        assignee: '',
        component: '',
        creationDate: '2022-12-28, 19:25:25',
        labels: 'HelpNeeded',
        priority: 1,
        resolutionDate: null,
        status: 'New',
        summary: 'پرتال تحلیل عملکرد- بروز خطا هنگام اجرای مایگریشن فریمورک روی یک دیتابیس خاص',
        version: 21,
        sla: -912304,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 435848,
        key: 'DATALM-95038',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95038',
        assignee: 'میلاد نفر',
        component: 'IST TDW',
        creationDate: '2022-12-31, 16:36:45',
        labels: 'PureView',
        priority: 2,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'نمایش جستجو در مد PureView دشبورد',
        version: 21,
        sla: -584683,
        slaColor: 'قرمز',
        starCis: 'PAPortal | BaseInfo',
    },
    {
        id: 434768,
        key: 'DATALM-95009',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95009',
        assignee: 'پارسا اروانه',
        component: 'IST TDW',
        creationDate: '2022-12-26, 21:06:24',
        labels: 'OldGrid',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'اسکرول نشدن در گزارش های گیرید',
        version: 21,
        sla: -356496,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 433516,
        key: 'DATALM-94887',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94887',
        assignee: 'بیژن عیسی‌پور',
        component: 'MOH LES',
        creationDate: '2022-12-22, 22:12:48',
        labels: 'HelpNeeded',
        priority: 2,
        resolutionDate: null,
        status: 'New',
        summary: 'متوقف شدن سرویس PADW بعد از تازه سازی داشبورد',
        version: 21,
        sla: -293432,
        slaColor: 'قرمز',
        starCis: 'PADW',
    },
    {
        id: 437425,
        key: 'DATALM-95101',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95101',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2023-01-04, 14:08:54',
        labels: 'MohaymenGrid | ObjectFramework',
        priority: 3,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'کارنکردن بخش نمایش تایل در سطل بازیافت',
        version: 25,
        sla: -10896,
        slaColor: 'قرمز',
        starCis: 'PAPortal',
    },
    {
        id: 434266,
        key: 'DATALM-94956',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94956',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-12-25, 16:11:06',
        labels: 'ObjectFramework',
        priority: 5,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خالی بودن دراپ دون آدرس',
        version: 25,
        sla: 17904,
        slaColor: 'زرد',
        starCis: 'PAPortal',
    },
    {
        id: 427631,
        key: 'DATALM-94145',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94145',
        assignee: 'میلاد نفر',
        component: '',
        creationDate: '2022-12-05, 15:37:22',
        labels: 'MohaymenGrid',
        priority: 6,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'نادرست بودن تعداد انتخاب‌شده‌ها در گیرید',
        version: 24,
        sla: 104303,
        slaColor: 'آبی',
        starCis: 'PAPortal',
    },
    {
        id: 428100,
        key: 'DATALM-94166',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94166',
        assignee: 'میلاد نفر',
        component: '',
        creationDate: '2022-12-07, 07:48:33',
        labels: 'UI',
        priority: 6,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'تغییر نام الگو بدون زدن دکمه ذخیره',
        version: 24,
        sla: 277103,
        slaColor: 'آبی',
        starCis: 'PAPortal',
    },
    {
        id: 437725,
        key: 'DATALM-95117',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95117',
        assignee: 'میلاد نفر',
        component: '',
        creationDate: '2023-01-05, 13:40:43',
        labels: 'DisplayConfigs',
        priority: 4,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خراب شدن گزارش در صورتی که پس زمینه Transparent باشد',
        version: 24,
        sla: 277103,
        slaColor: 'آبی',
        starCis: 'PAPortal',
    },
    {
        id: 435270,
        key: 'DATALM-95024',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95024',
        assignee: 'میلاد نفر',
        component: 'MCI FMRA',
        creationDate: '2022-12-29, 17:55:30',
        labels: 'DisplayConfigs',
        priority: 5,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'عدم تغییر رنگ عنوان نمودار نقشه و درختی',
        version: 21,
        sla: 277103,
        slaColor: 'آبی',
        starCis: 'PAPortal',
    },
    {
        id: 438631,
        key: 'DATALM-95151',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95151',
        assignee: '',
        component: '',
        creationDate: '2023-01-08, 13:35:29',
        labels: '',
        priority: 4,
        resolutionDate: null,
        status: 'New',
        summary: 'مشاهده خطای سینتکس موقع استفاده از یک جدول خاط',
        version: 24,
        sla: 449903,
        slaColor: 'آبی',
        starCis: 'PAPortal',
    },
    {
        id: 438785,
        key: 'DATALM-95161',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95161',
        assignee: '',
        component: 'IST TDW',
        creationDate: '2023-01-08, 17:13:27',
        labels: '',
        priority: 4,
        resolutionDate: null,
        status: 'New',
        summary: 'خطای در نمایش گزارش های جریان داده ای هنگام ذخیره سناریو',
        version: 21,
        sla: 449903,
        slaColor: 'آبی',
        starCis: 'PAPortal',
    },
    {
        id: 430836,
        key: 'DATALM-94555',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94555',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2022-12-14, 14:19:51',
        labels: 'DashboardSettings',
        priority: 6,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'دو باگ UI',
        version: 25,
        sla: 795503,
        slaColor: 'سبز',
        starCis: 'PAPortal',
    },
    {
        id: 432434,
        key: 'DATALM-94788',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94788',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2022-12-19, 15:04:48',
        labels: 'Toolbar',
        priority: 6,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'جابجاشدن آیکن تنظیمات فریم گزارش',
        version: 25,
        sla: 1141103,
        slaColor: 'سبز',
        starCis: 'PAPortal',
    },
    {
        id: 432853,
        key: 'DATALM-94817',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94817',
        assignee: 'بیژن عیسی‌پور',
        component: 'MOH LES',
        creationDate: '2022-12-20, 15:16:19',
        labels: 'FurtherInvestigationNeeded',
        priority: 6,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'مشاهده خطای Object reference هنگام لود داشبورد',
        version: 21,
        sla: 1227503,
        slaColor: 'سبز',
        starCis: 'PAPortal',
    },
    {
        id: 432752,
        key: 'DATALM-94813',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94813',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-12-20, 12:30:19',
        labels: 'UI',
        priority: 6,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'تایتل انگلیسی در سامانه فارسی',
        version: 24,
        sla: 1227503,
        slaColor: 'سبز',
        starCis: 'PAPortal',
    },
    {
        id: 433114,
        key: 'DATALM-94853',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94853',
        assignee: 'بیژن عیسی‌پور',
        component: 'BMK FMS',
        creationDate: '2022-12-21, 11:52:35',
        labels: 'HelpNeeded',
        priority: 6,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'خطای طول رشته مجاز برای گزارش استعلامی PA از DIA',
        version: 21,
        sla: 1313903,
        slaColor: 'سبز',
        starCis: 'DIAP | PAPortal',
    },
    {
        id: 437286,
        key: 'DATALM-95093',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95093',
        assignee: 'بیژن عیسی‌پور',
        component: '',
        creationDate: '2023-01-04, 10:08:08',
        labels: 'DateTime',
        priority: 6,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'گرید - عدم نمایش لیست اشیاء بعد پاک نمودن مقدار از فیلتر در ستون‌های تاریخ/زمان',
        version: 25,
        sla: 2264303,
        slaColor: 'سبز',
        starCis: 'PAPortal',
    },
    {
        id: 438517,
        key: 'DATALM-95144',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95144',
        assignee: '',
        component: 'BMK INI',
        creationDate: '2023-01-08, 10:32:40',
        labels: '',
        priority: 6,
        resolutionDate: null,
        status: 'New',
        summary: 'مشکل در sort  گزارشات گرید',
        version: 21,
        sla: 2523503,
        slaColor: 'سبز',
        starCis: 'PAPortal',
    },
    {
        id: 438508,
        key: 'DATALM-95143',
        link: 'https://jira.mohaymen.ir/browse/DATALM-95143',
        assignee: '',
        component: 'BMK INI',
        creationDate: '2023-01-08, 10:25:38',
        labels: '',
        priority: 6,
        resolutionDate: null,
        status: 'New',
        summary: 'اشکال در اسکرول گزارش داشبورد',
        version: 21,
        sla: 2523502,
        slaColor: 'سبز',
        starCis: 'PAPortal',
    },
    {
        id: 430402,
        key: 'DATALM-94360',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94360',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-12-13, 10:57:20',
        labels: 'MohaymenGrid',
        priority: 7,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'هاور سطرهای Mohaymen grid',
        version: 25,
        sla: 13669102,
        slaColor: 'سبز',
        starCis: 'PAPortal',
    },
    {
        id: 432011,
        key: 'DATALM-94770',
        link: 'https://jira.mohaymen.ir/browse/DATALM-94770',
        assignee: 'پارسا اروانه',
        component: '',
        creationDate: '2022-12-18, 14:20:54',
        labels: 'DisplayConfigs',
        priority: 7,
        resolutionDate: null,
        status: 'Confirmed',
        summary: 'بهم ریختن نمایش گزارش با زاویه 180',
        version: 25,
        sla: 14530292,
        slaColor: 'سبز',
        starCis: 'PAPortal',
    },
];
